.TH CLERR "1" "May 2016" "clerr 1.0.3" ""

.SH NAME
clerr \- colorize error output
.SH SYNOPSIS
\fBclerr\fR
[\fB-1hV\fR]
[\fB-c\fR \fICOLOR\fR]
\fICOMMAND\fR
[\fIARGUMENTS\fR...]
.SH DESCRIPTION
\fBclerr\fR is a command line tool which executes another \fICOMMAND\fR and colorizes all error output (on stderr) of that program while its normal output (on stdout) will be printed in the default colors.
.SH OPTIONS
.TP
.B \-1
All output will be printed on stdout only, even error output (which will still get colorized).
.TP
.B \-c \fICOLOR
Sets the color for error output.
Default is \fIred\fR.
Valid colors and their valid abbreviations are:

.IR red / re / rd ,
.IR green / gr / gn ,
.IR blue / bl ,
.IR yellow / ye / yw ,
.IR cyan / cy / cn ,
.IR white / wh .
.TP
.B \-h
Prints a short help summary and exits.
.TP
.B \-V
Prints the program version and exits.
.SH EXIT STATUS
\fBclerr\fR will exit with the same status as \fICOMMAND\fR,
if it was executed successfully.
If the command was terminated due to a signal,
\fBclerr\fR will kill itself with the same signal.
Otherwise, \fBclerr\fR will return one of these special exit status values:
.TP
.B 1
invocation error
(e.g. syntax error or unknown option)
.TP
.B 124
\fICOMMAND\fR could not be executed
.TP
.B 125
internal error
(e.g. could not fork)
.SH EXAMPLES
.TP
.B clerr cat /etc/group-
This will display the file \fI/etc/group-\fR in standard colors.
If the file does not exist or the caller is not permitted to read this file, the corresponding error message (something like "cat: /etc/group-: No such file or directory") will be printed in red.
.TP
.B clerr make
Run \fBmake\fR in the current directory. Any compiling errors will be printed in red.
.SH LICENSE
GNU GPL v3
<http://gnu.org/licenses/gpl.html>
.SH AUTHOR
Maximilian Eul <maximilian@eul.cc>
